### ISSUE TITLE
CAR TODOs

### ISSUE THREAD

**Issue by jean-lucas** [jean-lucas/vic#1]
- [x] Lane following
- [ ] Intersection detection
- [x] obstacle detection
- [ ] slow down at an approaching intersection
- [x] order parts for car num.  2
- [x] Install a camera tower on the car
- [ ] format a send request to the IC
- [x] update on response from IC
- [x] setup cars so they do not need Ethernet cables to run (jean has an idea)
- [x] Copy environment of one Pi to the other
- [x] Figure out the logic with the camera's FPS and car speed wrt the timing constraint of a program iteration
- [x] build car 2 - @justinerick ( ͡° ͜ʖ ͡°)

**Comment by justinerick** [comment]
https://gist.github.com/justinerick/7bc7da6eebc8ced7b5ef7d011c5cbe52

**Comment by jean-lucas** [comment]
https://gist.github.com/jean-lucas/bba16e99713e7b0ed7404ee0fbf5ff7c
